title: "Pure de Arch"
description: "Fedezd fel a Linux Desktop világát"
markdown: kramdown
theme: minima

collections:
  de:
    output: true
    permalink: /de/:name/
  wm:
    output: true
    permalink: /wm/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
