title: "Pure de Arch"
description: "Fedezd fel a Linux Desktop világát"
theme: minima
markdown: kramdown

collections:
  de:
    output: false
  wm:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
