title: Desktop Environment Comparison
description: Modern desktop environment comparison
theme: minima
markdown: kramdown

collections:
  - desktops

exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
